/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as FondationRouteImport } from './routes/fondation'
import { Route as InscriptionRouteImport } from './routes/inscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const FondationRoute = FondationRouteImport.update({
  id: '/fondation',
  path: '/fondation',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/fondation': typeof FondationRoute
  '/inscription': typeof InscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/fondation': typeof FondationRoute
  '/inscription': typeof InscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/fondation': typeof FondationRoute
  '/inscription': typeof InscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evenements' | '/fondation' | '/inscription'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evenements' | '/fondation' | '/inscription'
  id: '__root__' | '/' | '/evenements' | '/fondation' | '/inscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvenementsRoute: typeof EvenementsRoute
  FondationRoute: typeof FondationRoute
  InscriptionRoute: typeof InscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondation': {
      id: '/fondation'
      path: '/fondation'
      fullPath: '/fondation'
      preLoaderRoute: typeof FondationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvenementsRoute: EvenementsRoute,
  FondationRoute: FondationRoute,
  InscriptionRoute: InscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
